import { Inter } from "next/font/google";
import "./globals.css";
import "./css/bootstrap.min.css"
import "./css/bootstrap-icons.css"
// import "./css/owl.carousel.min.css"
import "./css/owl.theme.default.min.css"
import "./css/tooplate-gotto-job.css"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Degree Recommendation</title>

        <link rel="preconnect" href="https://fonts.googleapis.com" />

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />

        <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100;300;400;600;700&display=swap" rel="stylesheet" />

        <link href="./css/bootstrap.min.css" rel="stylesheet" />

        <link href="./css/bootstrap-icons.css" rel="stylesheet" />

        <link href="./css/owl.carousel.min.css" rel="stylesheet" />

        <link href="./css/owl.theme.default.min.css" rel="stylesheet" />

        <link href="./css/tooplate-gotto-job.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
